/*
 * OptionsEnumerationCustomizer.java
 *
 * Created on January 25, 2009, 6:12 PM
 */

package org.netbeans.modules.web.stripes.palette.items;

import javax.swing.text.JTextComponent;
import org.netbeans.modules.web.stripes.palette.CodeSnippet;
import org.netbeans.modules.web.stripes.palette.CodeSnippetCustomizer;
import org.netbeans.modules.web.stripes.palette.StripesPaletteUtilities;
import org.netbeans.modules.web.stripes.util.StringUtils;
import org.netbeans.modules.web.stripes.util.browse.BrowseDialogs;

/**
 *
 * @author  Josef Sustacek
 */
public class OptionsEnumerationCustomizer extends CodeSnippetCustomizer {

    private JTextComponent target;
    
    /** Creates new form OptionsEnumerationCustomizer */
    public OptionsEnumerationCustomizer(CodeSnippet codeSnippet, JTextComponent target) {
        super(codeSnippet);
        
        this.target = target;
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enumText = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(OptionsEnumerationCustomizer.class, "OptionsEnumerationCustomizer.jLabel1.text")); // NOI18N

        enumText.setText(org.openide.util.NbBundle.getMessage(OptionsEnumerationCustomizer.class, "OptionsEnumerationCustomizer.enumText.text")); // NOI18N

        browseBtn.setText(org.openide.util.NbBundle.getMessage(OptionsEnumerationCustomizer.class, "OptionsEnumerationCustomizer.browseBtn.text")); // NOI18N
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enumText, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(browseBtn)
                    .addComponent(enumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
    String enumFQN = BrowseDialogs.javaSourcesDialog(
            StripesPaletteUtilities.getProject(target), this);
    
    if(!StringUtils.nullOrEmpty(enumFQN)){
        enumText.setText(enumFQN);
    }
}//GEN-LAST:event_browseBtnActionPerformed

    @Override
    protected void evaluateInput() {
        codeSnippet.setProperty(OptionsEnumeration.ENUM, enumText.getText());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JTextField enumText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
